#!/bin/bash

bspc config border_width          1
bspc config window_gap            5

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

bspc monitor -d web irc mutt 4 5 6 7 8 9 0
bspc desktop irc -l monocle
bspc desktop web -l monocle
bspc desktop mutt -l monocle
bspc desktop 7 --toggle floating=on


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Wizard101 desktop=^7 follow=on floating=on
bspc rule -a Chromium desktop=^4
bspc rule -a Firefox desktop=^1
bspc rule -a Dwb desktop=^1 fullscreen=on
bspc rule -a mpv floating=on
bspc rule -a vlc floating=on
bspc rule -a Weechat desktop=^2 follow=on fullscreen=on
bspc rule -a qemu-system-x86_64 floating=on
bspc rule -a sun-awt-X11-XFramePeer floating=on

bspc config -m focused top_padding 15

. ~/font
~/others/wmname/wmname LG3D
mybar
